#!/bin/bash

mkdir $1
touch ./$1/$1.cpp
echo "#include <iostream>

using namespace std;

int main() {

    return 0;
}" >> ./$1/$1.cpp

touch ./$1/$1.in
touch ./$1/$1.out
touch ./$1/result.txt

touch Makefile
echo "
make: 
        g++ $1.cpp -std=c++11 
        ./a.out < $1.in > result.txt 
        diff result.txt 2158.out
"
