#!/bin/bash

mkdir $1
touch ./$1/$1.cpp
echo "#include <iostream>

using namespace std;

int main() {
    return 0;
}" >> ./$1/$1.cpp

touch ./$1/$1.in
touch ./$1/$1.out
touch ./$1/result.txt

touch ./$1/Makefile
echo -e "make:
\tg++ $1.cpp -std=c++11
\t./a.out < $1.in > result.txt
\tdiff result.txt $1.out
" >> ./$1/Makefile
